"""Add top_candidate, top_candidate_price on PerformanceProfile

Revision ID: 5f72a9f8b2d2
Revises: 42ae31e22f84
Create Date: 2023-07-13 13:50:16.402850

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5f72a9f8b2d2'
down_revision = '42ae31e22f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_profile', sa.Column('top_candidate', sa.String(length=25), nullable=True))
    op.add_column('performance_profile', sa.Column('top_candidate_price', sa.Float(), nullable=True))
    update_top_candidate_and_top_candidate_price_for_existing_profiles()
    op.create_index('Index for instance types', 'performance_profile', ['top_candidate'], unique=False)
    # ### end Alembic commands ###


def update_top_candidate_and_top_candidate_price_for_existing_profiles():
    try:
        print('Updating top_candidate and top_candidate_price for existing PerformanceProfile records!')
        op.execute("update performance_profile set top_candidate = subquery.top_candidate, top_candidate_price = cast("
                   "subquery.top_candidate_price as double precision) from (select rule_hit_details #> '{0,details,"
                   "candidates,0,0}' as top_candidate, rule_hit_details #> '{0,details,candidates,0,"
                   "1}' as top_candidate_price, system_id from performance_profile) as subquery where "
                   "performance_profile.system_id = subquery.system_id")
    except sa.exc.SQLAlchemyError as err:
        print(f"Failed to update table with error {err}!")
    else:
        print('Successfully updated top_candidate and top_candidate_price for existing PerformanceProfile records!')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Index for instance types', table_name='performance_profile')
    op.drop_column('performance_profile', 'top_candidate_price')
    op.drop_column('performance_profile', 'top_candidate')
    # ### end Alembic commands ###
