"""Add top_candidate, top_candidate_price on PerformanceProfile

Revision ID: 5f72a9f8b2d2
Revises: 42ae31e22f84
Create Date: 2023-07-13 13:50:16.402850

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '5f72a9f8b2d2'
down_revision = '42ae31e22f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_profile', sa.Column('top_candidate', sa.String(length=25), nullable=True))
    op.add_column('performance_profile', sa.Column('top_candidate_price', sa.Float(), nullable=True))
    op.create_index('Index for instance types', 'performance_profile', ['top_candidate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Index for instance types', table_name='performance_profile')
    op.drop_column('performance_profile', 'top_candidate_price')
    op.drop_column('performance_profile', 'top_candidate')
    # ### end Alembic commands ###
